### ISSUE TITLE
TOTP support - copy token to clipboard after typing password

### ISSUE THREAD

**Issue by ai212983** [mooltipass/extension#162]
Hello guys.

I know #95 exists, but AFAIK extension currently is not handling TOTP in any way. Manual refers only to device TOTP support.

My usecase:  
 - Entering username and password at Paypal.com automagically with your awesome extension
 - Go to my Mooltipass, skip typing login, skip typing password, type TOTP

It would be great if the extension could detect if the entry for which it just typed a password has a TOTP token and then copy it to the clipboard. 

Thanks!

**Comment by limpkin** [comment]
hey there!
Can't believe I didn't get to this issue. At the moment we have several options:
- right click on the field, select Mooltipass extension, and select "Fetch TOTP code"
- select "display TOTP after login into website" in moolticute settings (my favorite option)
I'm not sure I'm a big fan to store totp in the clipbard due to security reasons...
